### Pandas Practice

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("../data/fatal-police-shootings-data.csv",
                   parse_dates=["date"])

In [4]:
data.head()

,id,date,threat_type,flee_status,armed_with,city,county,state,latitude,longitude,location_precision,name,age,gender,race,race_source,was_mental_illness_related,body_camera,agency_ids
0,3,2015-01-02,point,not,gun,Shelton,Mason,WA,47.246826,-123.121592,not_available,Tim Elliot,53.0,male,A,not_available,True,False,73
1,4,2015-01-02,point,not,gun,Aloha,Washington,OR,45.487421,-122.891696,not_available,Lewis Lee Lembke,47.0,male,W,not_available,False,False,70
2,5,2015-01-03,move,not,unarmed,Wichita,Sedgwick,KS,37.694766,-97.280554,not_available,John Paul Quintero,23.0,male,H,not_available,False,False,238
3,8,2015-01-04,point,not,replica,San Francisco,San Francisco,CA,37.762910,-122.422001,not_available,Matthew Hoffman,32.0,male,W,not_available,True,False,196
4,9,2015-01-04,point,not,other,Evans,Weld,CO,40.383937,-104.692261,not_available,Michael Rodriguez,39.0,male,H,not_available,False,False,473

In [5]:
data.sort_values(by="state",ascending=True)

,id,date,threat_type,flee_status,armed_with,city,county,state,latitude,longitude,location_precision,name,age,gender,race,race_source,was_mental_illness_related,body_camera,agency_ids
6130,6676,2021-03-06,point,NaN,gun,Fairbanks,NaN,AK,64.823807,-147.869544,not_available,Jessie Peter,27.0,male,W,not_available,False,False,3058;775
8660,9664,2023-07-02,threat,not,gun,Anchorage,Anchorage,AK,61.366650,-149.534811,poi_small,Sean M. Burke,34.0,male,NaN,NaN,False,False,208
2350,2618,2017-05-25,shoot,car,gun,Fairbanks,NaN,AK,NaN,NaN,NaN,Shawn Buck,23.0,male,W,not_available,False,False,776
1521,1707,2016-07-12,attack,not,knife,Anchorage,Anchorage,AK,61.218414,-149.813983,not_available,Benjamin Zeckovic,23.0,male,W,not_available,True,False,208
3840,4201,2018-11-22,threat,foot,knife,Palmer,NaN,AK,NaN,NaN,NaN,Cameron McCarthy,20.0,male,W,not_available,False,False,775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10159,11159,2024-10-05,point,NaN,gun,Sundance,Crook,WY,NaN,NaN,NaN,Joseph Keith Neimeyer,48.0,male,W,clip,False,False,3527
6918,7477,2021-12-06,shoot,not,gun,Basin,NaN,WY,NaN,NaN,NaN,Dale Vincent Query,38.0,male,W,photo,True,False,3302
3337,3673,2018-05-06,shoot,not,gun,Casper,Natrona,WY,42.835296,-106.297873,not_available,David P. Wolosin,38.0,male,W,not_available,False,False,647
7218,7982,2022-03-18,shoot,not,gun,Evansville,NaN,WY,42.864247,-106.268943,not_available,Blaine Patrick Clutter,29.0,male,W,photo,False,False,647
7716,8650,2022-08-30,point,car,gun,Powell,Park,WY,NaN,NaN,NaN,Jack McGlothin,37.0,male,W,photo,False,False,3633

In [6]:
data.columns
len(data)

10430

In [7]:
data["threat_type"].value_counts()

threat_type
shoot           2924
threat          2674
point           1890
attack          1490
move             599
undetermined     538
flee             192
accident          55
Name: count, dtype: int64

In [8]:
data["threat_type"].sort_values(ascending=False)

10040    undetermined
6385     undetermined
2457     undetermined
7497     undetermined
1719     undetermined
             ...
9230              NaN
9263              NaN
9466              NaN
9720              NaN
9876              NaN
Name: threat_type, Length: 10430, dtype: str

In [9]:
data["accidental"] = data["threat_type"] == "accident"

In [10]:
data.columns

Index(['id', 'date', 'threat_type', 'flee_status', 'armed_with', 'city',
       'county', 'state', 'latitude', 'longitude', 'location_precision',
       'name', 'age', 'gender', 'race', 'race_source',
       'was_mental_illness_related', 'body_camera', 'agency_ids',
       'accidental'],
      dtype='str')

In [11]:
accidental_killings = data[ data["threat_type"] == "accident" ]
accidental_killings.value_counts("armed_with")

armed_with
unarmed          46
gun               5
undetermined      3
vehicle;knife     1
Name: count, dtype: int64

In [12]:
data["threat_type"].describe()

count     10362
unique        8
top       shoot
freq       2924
Name: threat_type, dtype: object

In [14]:
data.groupby(
    ["state"]
    )["age"].median(

    ).reset_index(

    ).sort_values(
        by="age",
        ascending=True
    )

   state   age
8     DE  30.0
7     DC  31.0
14    IL  32.0
20    MD  33.0
23    MN  33.0
35    OH  34.0
34    NY  34.0
29    NE  34.0
28    ND  34.0
24    MO  34.0
11    HI  34.0
0     AK  34.0
3     AZ  34.0
4     CA  34.0
43    TX  34.5
12    IA  35.0
32    NM  35.0
44    UT  35.0
10    GA  35.0
5     CO  35.0
26    MT  35.0
41    SD  35.0
46    VT  35.0
38    PA  36.0
6     CT  36.0
19    MA  36.0
37    OR  36.0
18    LA  36.0
36    OK  36.0
16    KS  36.0
15    IN  36.0
47    WA  36.0
48    WI  37.0
2     AR  37.0
21    ME  37.0
27    NC  37.0
45    VA  37.0
22    MI  37.0
33    NV  37.0
9     FL  37.0
40    SC  37.5
42    TN  38.0
25    MS  38.0
31    NJ  38.0
30    NH  38.0
17    KY  38.0
1     AL  38.0
13    ID  39.0
50    WY  39.0
49    WV  42.5
39    RI  44.5

In [41]:
data.columns

Index(['id', 'date', 'threat_type', 'flee_status', 'armed_with', 'city',
       'county', 'state', 'latitude', 'longitude', 'location_precision',
       'name', 'age', 'gender', 'race', 'race_source',
       'was_mental_illness_related', 'body_camera', 'agency_ids',
       'accidental'],
      dtype='str')

In [49]:
data.groupby(
    ["state", "race"]
).agg(
    {
        "age":"mean"
    }
).sort_values(
    by="state",
    ascending=True
)

                  age
state race
AK    A     30.666667
      B     38.000000
      N     29.153846
      O     16.000000
      W     36.057143
...               ...
WV    B     37.600000
WY    H     41.500000
      N     38.000000
      B     35.000000
      W     38.040000

[228 rows x 1 columns]

In [61]:
# Figure out which state had the most shootings

data["state"].value_counts().sort_values(ascending=True)

state
RI       8
VT      15
DE      22
ND      27
DC      30
CT      32
NH      33
SD      35
WY      36
HI      47
ME      49
NE      49
MA      61
IA      63
MT      69
AK      69
ID      90
KS      99
WV     100
MN     107
NJ     108
MD     129
UT     133
MS     139
AR     143
WI     163
OR     166
SC     171
NV     171
KY     179
MI     187
NY     199
VA     199
AL     200
LA     200
IL     212
IN     214
NM     219
PA     227
MO     263
OK     266
WA     277
TN     293
OH     305
NC     310
CO     375
GA     393
AZ     461
FL     672
TX    1010
CA    1405
Name: count, dtype: int64

In [69]:
# What's the average age of the victims in the dataset?

data["age"].describe()

count    10058.000000
mean        37.464705
std         12.931090
min          0.000000
25%         28.000000
50%         35.000000
75%         45.000000
max         92.000000
Name: age, dtype: float64

In [ ]:
# Figure out the average age of unarmed victims per state

data.groupby(
    ["state"]
).agg(
    {"age":"mean"}
).reset_index(

).sort_values(
    by="age",
    ascending=True
)

   state        age
7     DC  32.900000
14    IL  33.971154
8     DE  34.772727
28    ND  34.962963
0     AK  34.971014
23    MN  35.271028
12    IA  35.476190
4     CA  35.800000
20    MD  35.960938
24    MO  36.023810
43    TX  36.523904
5     CO  36.549858
32    NM  36.629268
44    UT  36.732283
3     AZ  36.738636
29    NE  36.836735
35    OH  36.866221
19    MA  37.118644
41    SD  37.121212
36    OK  37.290837
16    KS  37.292929
47    WA  37.445693
18    LA  37.534031
22    MI  37.585227
11    HI  37.652174
37    OR  37.705521
10    GA  37.884319
25    MS  37.956522
34    NY  38.010101
6     CT  38.032258
15    IN  38.075829
38    PA  38.098214
26    MT  38.151515
30    NH  38.333333
31    NJ  38.580952
45    VA  38.601036
48    WI  38.645963
33    NV  38.790419
50    WY  38.805556
21    ME  39.020408
27    NC  39.063333
9     FL  39.171384
42    TN  39.399306
2     AR  39.970803
1     AL  40.036842
40    SC  40.088235
17    KY  40.090361
13    ID  41.116279
46    VT  41.200000
49    WV  43.534091
39    RI  45.375000

In [15]:
# Figure out how many cases were mental illness related

data["was_mental_illness_related"].value_counts()

was_mental_illness_related
False    8373
True     2057
Name: count, dtype: int64

In [16]:
# ... as a percent over the total?
percent_mental_illness_related = data["was_mental_illness_related"].value_counts()[True] / len(data) * 100

print(percent_mental_illness_related)

# remember: .value_counts() counts occurrences of values

19.721955896452542

In [17]:
# Group the data by city and state. Which city had the most shootings?

data.groupby(
    ["city", "state"]
).size().sort_values(ascending=False)

# size() on the other hand counts rows in a group!

city         state
Los Angeles  CA       157
Phoenix      AZ       130
Houston      TX       125
San Antonio  TX       101
Las Vegas    NV        86
                     ...
Hermitage    MO         1
             TN         1
Hernando     FL         1
             MS         1
Еasley       SC         1
Length: 4419, dtype: int64