## Doing basic analyses with Python



##### Clarifying our research objective
For this exercise, we’re working with [citywide payroll data from NYC Open Data](https://data.cityofnewyork.us/City-Government/Citywide-Payroll-Data-Fiscal-Year-/k397-673e/about_data).

As usual, let's start by importing pandas:

In [2]:
import pandas as pd

Then, let's import our data:

In [64]:
data_types = {
    "Base Salary":float
}
date_cols  = ["Fiscal Year", "Agency Start Date"]


data = pd.read_csv(
        '../data/Citywide_Payroll_Data__Fiscal_Year__20240616.csv', 
        low_memory=False,
        dtype=data_types,
        parse_dates=date_cols
    )

len(data)

552938

Let's look at the top 10 entries of our data.

In [25]:
data.head()

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay
0,2023,67,ADMIN FOR CHILDREN'S SVCS,ROODE,SELENA,R,07/22/2019,BRONX,CHILD PROTECTIVE SPECIALIST,ACTIVE,65921.0,per Annum,1820.0,65977.23,6.50,244.34,4400.66
1,2023,67,ADMIN FOR CHILDREN'S SVCS,AARON,TERESA,NaN,03/21/2016,BRONX,CHILD PROTECTIVE SPECIALIST,ACTIVE,65921.0,per Annum,1820.0,65998.30,448.00,22072.10,15938.80
2,2023,67,ADMIN FOR CHILDREN'S SVCS,AARONS,CAMELIA,M,08/08/2016,BROOKLYN,CHILD PROTECTIVE SPECIALIST,ON LEAVE,65921.0,per Annum,602.0,23163.11,28.75,1295.17,8994.61
3,2023,67,ADMIN FOR CHILDREN'S SVCS,ABBASSI,MARIAM,N,11/21/2022,QUEENS,CHILD PROTECTIVE SPECIALIST,ACTIVE,55463.0,per Annum,1050.0,31082.77,27.75,928.43,3115.50
4,2023,67,ADMIN FOR CHILDREN'S SVCS,ABDEL WEDOUD,LASHAWN,NaN,04/24/2023,BROOKLYN,YOUTH DEVELOPMENT SPECIALIST,ACTIVE,50001.0,per Annum,280.0,7792.26,0.00,0.00,0.00

In [26]:
data.tail()

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay
552933,2023,858,TECHNOLOGY & INNOVATION,FERRARI,MICHAEL,J,11/15/2004,MANHATTAN,ADM MANAGER-NON-MGRL,ACTIVE,120000.0,per Annum,1820.0,101069.00,45.5,2457.20,2892.16
552934,2023,858,TECHNOLOGY & INNOVATION,FERNANDO,SONAL,S,02/21/2012,BROOKLYN,COMPUTER SYSTEMS MANAGER,ACTIVE,181500.0,per Annum,1820.0,177521.86,0.0,17.51,243.26
552935,2023,858,TECHNOLOGY & INNOVATION,FERNANDEZ DE JE,YESENNY,NaN,03/27/2023,MANHATTAN,COMMUNITY COORDINATOR,ACTIVE,86500.0,per Annum,420.0,19154.09,0.0,0.00,3000.00
552936,2023,858,TECHNOLOGY & INNOVATION,FERNANDEZ,GABRIEL,L,06/06/2023,MANHATTAN,SUMMER COLLEGE INTERN,ACTIVE,17.5,per Hour,21.0,367.50,0.0,0.00,0.00
552937,2023,858,TECHNOLOGY & INNOVATION,FERNANDES,BENEDICT,L,02/03/2020,BROOKLYN,COMPUTER SYSTEMS MANAGER,CEASED,178200.0,per Annum,343.0,33491.24,0.0,0.00,2042.86

How big is our dataset?

How many columns does it have and what columns are there?

In [28]:
len(data.columns)

17

What data types are in it?

In [31]:
data.dtypes

Fiscal Year                   datetime64[us]
Payroll Number                         int64
Agency Name                              str
Last Name                                str
First Name                               str
Mid Init                                 str
Agency Start Date             datetime64[us]
Work Location Borough                    str
Title Description                        str
Leave Status as of June 30               str
Base Salary                          float64
Pay Basis                                str
Regular Hours                        float64
Regular Gross Paid                   float64
OT Hours                             float64
Total OT Paid                        float64
Total Other Pay                      float64
dtype: object

We should re-format a lot of the columns so we can work with them:

### Analysis: Asking the right questions

Let's get back to our research question:
- Which agency had the most employees?
- Whats the median, average, and highest pay for a city employee?
- Who are they?

We can use `.value_counts()` to do a quick 'pivot table' of any given column:

In [33]:
data["Title Description"].value_counts()

Title Description
TEACHER- PER SESSION                                            79950
TEACHER                                                         56489
ELECTION WORKER                                                 29686
TEACHER SPECIAL EDUCATION                                       29228
ANNUAL ED PARA                                                  28225
                                                                ...
Deputy Commissioner Film Office                                     1
Associate Commissioner                                              1
First Deputy Commissioner                                           1
Deputy Commissioner                                                 1
COMMISSIONER OF DEPT OF INFO TECHNOLOGY & TELECOMMUNICATIONS        1
Name: count, Length: 1535, dtype: int64

We can use `.describe()` to get an overview of the data in a column. 

The function reveals various characteristics of your data column. Below is a breakdown. 

```
count    <-- how many rows there are in your data column
mean     <-- the average value of the entire 
std      <-- the standard deviation, which measures how much the values in the series deviate from the mean
min      <-- the smallest number in the data columnst
25%      <-- the 25th percentile or first quartile in the data column
50%      <-- the 50th percentile or median in the data column
75%      <-- the 75th percentile or third quartile in the data column
max      <-- highest number in the data column
Name: column_name, dtype: <-- what kind of data is in the column
```

In [ ]:
data["Base Salary"] = data["Base Salary"].replace("$","").replace(",","")

data["base_salary_float"] = data["Base Salary"].astype(float)

count    552938.000000
mean      51337.371450
std       48070.639384
min           1.000000
25%          33.180000
50%       48755.000000
75%       92073.000000
max      363346.000000
Name: Base Salary, dtype: float64

### Filtering your data for closer inspection

In [40]:
data.columns

data["Pay Basis"].value_counts()

Pay Basis
per Annum          338552
per Day            124341
per Hour            87696
Prorated Annual      2349
Name: count, dtype: int64

In [ ]:
data_reduced = data[data["Pay Basis"] == "per Annum"]

print(f"Rows in reduced dataset:  {len(data_reduced)} versus {len(data)} in the full dataset.")

Rows in reduced dataset:  338552 versus 552938 in the full dataset.

### Filtering your data to hone in on your results
Let's:
- narrow down our data to empoyees who work on an annual basis
- then let's redo some of the calculations

First let's find out what types of employment bases there are in our data:

In [ ]:
data["is_per_annum"] = data["Pay Basis"].apply(lambda x: "per annum" in str(x).lower().strip())

Let's say we only want people in the 

Remember to SELECT a subsection of our data we use brackets. 

Here's how this may work for different scenarios:

The base formula for this looks like this: `dataframe[ INSERT CRITERIA FOR SELECTION HERE]`

An example of reducing your dataframe down to selected columns:
```
columns = ["column_name1", "column_name2"]
dataframe[columns]
```

An example of reducing your dataframe down based on a condition (in this case, the dataframe will drop any row where the `salary` is below 10000:
```

dataframe[  dataframe["salary"] < 10000  ]
```

### Filter our data using a lambda function

For that we will:
- create a column that contains a Boolean, `True` or `False`, based on a condition
- filter down our data based on that condition

We can do this using `functions` like the ones we've learned about in early Python lessons that we declare using `def`. We can also do this using`lambda function` which are functions written in one line!

Below we do the same thing we did earlier to reduce our dataframe to only `"per Annum"` workers but with a bit more Python.

Now let's re-run some of our analyses:

I want to find out, for each type of worker category: what is the median salary?

In [ ]:
data.groupby(
    ["Title Description"]
)["Base Salary"].median(

).reset_index(
    
).sort_values(
    by="Base Salary",
    ascending=False
)

                    Title Description  Base Salary
358                        CHANCELLOR    363346.00
364                     CHIEF ACTUARY    318442.50
1130                        PRESIDENT    280908.00
907                FIRST DEPUTY MAYOR    275000.00
1055                            MAYOR    258750.00
...                               ...          ...
1396           SUBSTITUTE SCHOOL AIDE        14.37
1397   SUBSTITUTE SCHOOL LUNCH HELPER        14.37
1395  SUBSTITUTE RECREATION ASSISTANT        14.00
789                   ELECTION WORKER         1.00
788                  ELECTION TRAINER         1.00

[1535 rows x 2 columns]

In [52]:
data[data["Title Description"] == "PRESIDENT"]

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay
45312,2023-01-01,463,COMMUNITY COLLEGE (BRONX),ISEKENEGBE,THOMAS,A,2015-08-17,QUEENS,PRESIDENT,ACTIVE,280908.0,per Annum,1820.0,285256.42,0.0,0.0,60000.0
46325,2023-01-01,468,COMMUNITY COLLEGE (HOSTOS),COCCO DE FILIPP,DAISY,NaN,2002-01-15,BRONX,PRESIDENT,ACTIVE,283560.0,per Annum,1820.0,282706.86,0.0,0.0,60000.0
48211,2023-01-01,465,COMMUNITY COLLEGE (KINGSBORO),SCHRADER,CLAUDIA,NaN,2018-09-15,BROOKLYN,PRESIDENT,ACTIVE,280908.0,per Annum,1820.0,285256.90,0.0,0.0,60000.0
50265,2023-01-01,469,COMMUNITY COLLEGE (LAGUARDIA),ADAMS,KENNETH,G,2020-08-17,QUEENS,PRESIDENT,ACTIVE,280908.0,per Annum,1820.0,285389.05,0.0,0.0,60000.0
57190,2023-01-01,466,COMMUNITY COLLEGE (MANHATTAN),MUNROE,ANTHONY,E,2020-09-01,MANHATTAN,PRESIDENT,ACTIVE,280500.0,per Annum,1820.0,279656.06,0.0,0.0,60000.0
59792,2023-01-01,464,COMMUNITY COLLEGE (QUEENSBORO),MANGINO,CHRISTINE,NaN,2020-08-17,QUEENS,PRESIDENT,ACTIVE,280908.0,per Annum,1820.0,285389.05,0.0,0.0,60000.0
451794,2023-01-01,462,GUTTMAN COMMUNITY COLLEGE,JOHNSON,LARRY,D,2021-07-01,MANHATTAN,PRESIDENT,ACTIVE,260100.0,per Annum,1820.0,259317.57,0.0,0.0,60000.0
549544,2023-01-01,21,TAX COMMISSION,HENN,FRANCES,J,2016-05-02,MANHATTAN,PRESIDENT,ACTIVE,227786.0,per Annum,1820.0,227161.99,0.0,0.0,375.0

In [53]:
data.columns

Index(['Fiscal Year', 'Payroll Number', 'Agency Name', 'Last Name',
       'First Name', 'Mid Init', 'Agency Start Date', 'Work Location Borough',
       'Title Description', 'Leave Status as of June 30', 'Base Salary',
       'Pay Basis', 'Regular Hours', 'Regular Gross Paid', 'OT Hours',
       'Total OT Paid', 'Total Other Pay'],
      dtype='str')

In [ ]:
# Find the median base salary grouped by each agency and borough.

data.groupby( 
    ["Agency Name", "Work Location Borough"]
)["Base Salary"].median(
    
).reset_index().sort_values(
    by="Base Salary",
    ascending=False
)

                        Agency Name Work Location Borough  Base Salary
259             OFFICE OF THE MAYOR         WASHINGTON DC    154000.00
69    COMMUNITY COLLEGE (LAGUARDIA)                 BRONX    152939.00
181  DISTRICT ATTORNEY-SPECIAL NARC              BROOKLYN    145000.00
183  DISTRICT ATTORNEY-SPECIAL NARC                QUEENS    141250.00
250  OFFICE OF COLLECTIVE BARGAININ             MANHATTAN    140000.00
..                              ...                   ...          ...
274            PUBLIC SERVICE CORPS             MANHATTAN        16.00
166      DEPT OF PARKS & RECREATION           WESTCHESTER        15.91
260              PERSONNEL MONITORS             MANHATTAN        15.00
16   BOARD OF ELECTION POLL WORKERS              BROOKLYN         1.00
17   BOARD OF ELECTION POLL WORKERS             MANHATTAN         1.00

[300 rows x 3 columns]

In [ ]:
data.groupby(
    ["Agency Name", "Work Location Borough"]
).agg(
    {
        "Base Salary":"median",
        "Base Salary":"max",
        "Base Salary":"min"
    }
).reset_index(
    
).sort_values(
    by="Base Salary",
    ascending=False
)

                     Agency Name Work Location Borough  Base Salary
0      ADMIN FOR CHILDREN'S SVCS                 BRONX        29.85
1      ADMIN FOR CHILDREN'S SVCS              BROOKLYN        25.95
2      ADMIN FOR CHILDREN'S SVCS             MANHATTAN        22.36
3      ADMIN FOR CHILDREN'S SVCS                QUEENS        29.85
4      ADMIN FOR CHILDREN'S SVCS              RICHMOND     41100.00
..                           ...                   ...          ...
295  TAXI & LIMOUSINE COMMISSION                QUEENS        15.50
296   TEACHERS RETIREMENT SYSTEM             MANHATTAN        15.50
297      TECHNOLOGY & INNOVATION                 BRONX    135795.00
298      TECHNOLOGY & INNOVATION              BROOKLYN        17.30
299      TECHNOLOGY & INNOVATION             MANHATTAN        16.35

[300 rows x 3 columns]

In [3]:
police_data = pd.read_csv("../data/fatal-police-shootings-data.csv")

police_data.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/fatal-police-shootings-data.csv'

In [59]:
# Sort by state ascending.
police_data.sort_values(by="state", ascending=True)

,id,date,threat_type,flee_status,armed_with,city,county,state,latitude,longitude,location_precision,name,age,gender,race,race_source,was_mental_illness_related,body_camera,agency_ids
6130,6676,2021-03-06,point,NaN,gun,Fairbanks,NaN,AK,64.823807,-147.869544,not_available,Jessie Peter,27.0,male,W,not_available,False,False,3058;775
8660,9664,2023-07-02,threat,not,gun,Anchorage,Anchorage,AK,61.366650,-149.534811,poi_small,Sean M. Burke,34.0,male,NaN,NaN,False,False,208
2350,2618,2017-05-25,shoot,car,gun,Fairbanks,NaN,AK,NaN,NaN,NaN,Shawn Buck,23.0,male,W,not_available,False,False,776
1521,1707,2016-07-12,attack,not,knife,Anchorage,Anchorage,AK,61.218414,-149.813983,not_available,Benjamin Zeckovic,23.0,male,W,not_available,True,False,208
3840,4201,2018-11-22,threat,foot,knife,Palmer,NaN,AK,NaN,NaN,NaN,Cameron McCarthy,20.0,male,W,not_available,False,False,775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10159,11159,2024-10-05,point,NaN,gun,Sundance,Crook,WY,NaN,NaN,NaN,Joseph Keith Neimeyer,48.0,male,W,clip,False,False,3527
6918,7477,2021-12-06,shoot,not,gun,Basin,NaN,WY,NaN,NaN,NaN,Dale Vincent Query,38.0,male,W,photo,True,False,3302
3337,3673,2018-05-06,shoot,not,gun,Casper,Natrona,WY,42.835296,-106.297873,not_available,David P. Wolosin,38.0,male,W,not_available,False,False,647
7218,7982,2022-03-18,shoot,not,gun,Evansville,NaN,WY,42.864247,-106.268943,not_available,Blaine Patrick Clutter,29.0,male,W,photo,False,False,647
7716,8650,2022-08-30,point,car,gun,Powell,Park,WY,NaN,NaN,NaN,Jack McGlothin,37.0,male,W,photo,False,False,3633

In [60]:
police_data["state"].value_counts()

state
CA    1405
TX    1010
FL     672
AZ     461
GA     393
CO     375
NC     310
OH     305
TN     293
WA     277
OK     266
MO     263
PA     227
NM     219
IN     214
IL     212
LA     200
AL     200
VA     199
NY     199
MI     187
KY     179
NV     171
SC     171
OR     166
WI     163
AR     143
MS     139
UT     133
MD     129
NJ     108
MN     107
WV     100
KS      99
ID      90
MT      69
AK      69
IA      63
MA      61
NE      49
ME      49
HI      47
WY      36
SD      35
NH      33
CT      32
DC      30
ND      27
DE      22
VT      15
RI       8
Name: count, dtype: int64

In [61]:
# Create a sub-dataset for unarmed killings.
unarmed_killings = police_data[ police_data["armed_with"] == "unarmed" ]

In [62]:
len(unarmed_killings)

565