## Doing basic analyses with Python



##### Clarifying our research objective
For this exercise, we’re working with [citywide payroll data from NYC Open Data](https://data.cityofnewyork.us/City-Government/Citywide-Payroll-Data-Fiscal-Year-/k397-673e/about_data).

As usual, let's start by importing pandas:

In [4]:
%pip install pandas

Collecting pandas
  Using cached pandas-3.0.6-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.4-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/layla/.pyenv/versions/3.14.0/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/layla/.pyenv/versions/3.14.0/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.6-cp314-cp314-macosx_11_0_arm64.whl (10.2 MB)
Downloading numpy-2.5.4-cp314-cp314-macosx_14_0_arm64.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 7.6 MB/s  0:00:00 eta 0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.4 pandas-3.0.6

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

Then, let's import our data:

In [17]:
%%time
data = pd.read_csv('../data/Citywide_Payroll_Data__Fiscal_Year__20240616.csv')
print(len(data))

552938
CPU times: user 335 ms, sys: 25 ms, total: 360 ms
Wall time: 366 ms

Let's look at the top 10 entries of our data.

In [19]:
data.head()

data["Fiscal Year"].value_counts()

Fiscal Year
2023    552938
Name: count, dtype: int64

In [8]:
data.tail()

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay
552933,2023,858,TECHNOLOGY & INNOVATION,FERRARI,MICHAEL,J,11/15/2004,MANHATTAN,ADM MANAGER-NON-MGRL,ACTIVE,120000.0,per Annum,1820.0,101069.00,45.5,2457.20,2892.16
552934,2023,858,TECHNOLOGY & INNOVATION,FERNANDO,SONAL,S,02/21/2012,BROOKLYN,COMPUTER SYSTEMS MANAGER,ACTIVE,181500.0,per Annum,1820.0,177521.86,0.0,17.51,243.26
552935,2023,858,TECHNOLOGY & INNOVATION,FERNANDEZ DE JE,YESENNY,NaN,03/27/2023,MANHATTAN,COMMUNITY COORDINATOR,ACTIVE,86500.0,per Annum,420.0,19154.09,0.0,0.00,3000.00
552936,2023,858,TECHNOLOGY & INNOVATION,FERNANDEZ,GABRIEL,L,06/06/2023,MANHATTAN,SUMMER COLLEGE INTERN,ACTIVE,17.5,per Hour,21.0,367.50,0.0,0.00,0.00
552937,2023,858,TECHNOLOGY & INNOVATION,FERNANDES,BENEDICT,L,02/03/2020,BROOKLYN,COMPUTER SYSTEMS MANAGER,CEASED,178200.0,per Annum,343.0,33491.24,0.0,0.00,2042.86

How big is our dataset?

In [12]:
len(data)

552938

How many columns does it have and what columns are there?

In [10]:
print(len(data.columns))
data.columns

17

Index(['Fiscal Year', 'Payroll Number', 'Agency Name', 'Last Name',
       'First Name', 'Mid Init', 'Agency Start Date', 'Work Location Borough',
       'Title Description', 'Leave Status as of June 30', 'Base Salary',
       'Pay Basis', 'Regular Hours', 'Regular Gross Paid', 'OT Hours',
       'Total OT Paid', 'Total Other Pay'],
      dtype='str')

What data types are in it?

In [11]:
data.dtypes

Fiscal Year                     int64
Payroll Number                  int64
Agency Name                       str
Last Name                         str
First Name                        str
Mid Init                          str
Agency Start Date                 str
Work Location Borough             str
Title Description                 str
Leave Status as of June 30        str
Base Salary                   float64
Pay Basis                         str
Regular Hours                 float64
Regular Gross Paid            float64
OT Hours                      float64
Total OT Paid                 float64
Total Other Pay               float64
dtype: object

We should re-format a lot of the columns so we can work with them:

### Analysis: Asking the right questions

Let's get back to our research question:
- Agency had the most employees?
- Whats the median, average and highest pay for a city employee?
- Who are they?

We can use `.value_counts()` to do a quick 'pivot table' of any given column:

In [4]:
data["Agency Name"].value_counts()

Agency Name
DEPT OF ED PEDAGOGICAL            106882
DEPT OF ED PER SESSION TEACHER     82883
POLICE DEPARTMENT                  58617
DEPT OF ED PARA PROFESSIONALS      39580
BOARD OF ELECTION POLL WORKERS     29915
                                   ...
BRONX COMMUNITY BOARD #1               2
BRONX COMMUNITY BOARD #12              2
BROOKLYN COMMUNITY BOARD #12           2
BROOKLYN COMMUNITY BOARD #8            2
BRONX COMMUNITY BOARD #3               1
Name: count, Length: 156, dtype: int64

We can use `.describe()` to get an overview of the data in a column. 

The function reveals various characteristics of your data column. Below is a breakdown. 

```
count    <-- how many rows there are in your data column
mean     <-- the average value of the entire 
std      <-- the standard deviation, which measures how much the values in the series deviate from the mean
min      <-- the smallest number in the data columnst
25%      <-- the 25th percentile or first quartile in the data column
50%      <-- the 50th percentile or median in the data column
75%      <-- the 75th percentile or third quartile in the data column
max      <-- highest number in the data column
Name: column_name, dtype: <-- what kind of data is in the column
```

In [6]:
data["Base Salary"].describe()

count    552938.000000
mean      51337.371450
std       48070.639384
min           1.000000
25%          33.180000
50%       48755.000000
75%       92073.000000
max      363346.000000
Name: Base Salary, dtype: float64

### Filtering your data for closer inspection

In [19]:
print(len(data))
print(len(data[data["Base Salary"] > 200_000]))

552938
1145

### Filtering your data to hone in on your results
Let's:
- narrow down our data to empoyees who work on an annual basis
- then let's redo some of the calculations

First let's find out what types of employment bases there are in our data:

In [11]:

data["Pay Basis"].value_counts()

Pay Basis
per Annum          338552
per Day            124341
per Hour            87696
Prorated Annual      2349
Name: count, dtype: int64

Let's say we only want people in the 

Remember to SELECT a subsection of our data we use brackets. 

Here's how this may work for different scenarios:

The base formula for this looks like this: `dataframe[ INSERT CRITERIA FOR SELECTION HERE]`

An example of reducing your dataframe down to selected columns:
```
columns = ["column_name1", "column_name2"]
dataframe[columns]
```

An example of reducing your dataframe down based on a condition (in this case, the dataframe will drop any row where the `salary` is below 10000:
```

dataframe[  dataframe["salary"] < 10000  ]
```

In [12]:
data_reduced = data[data["Pay Basis"] ==  "per Annum"]

print(f"Number of rows for the original dataframe is \
{len(data)} and the number of rows for the reduced dataframe is {len(data_reduced)}")

Number of rows for the original dataframe is 552938 and the number of rows for the reduced dataframe is 338552

### Filter our data using a lambda function

For that we will:
- create a column that contains a Boolean, `True` or `False`, based on a condition
- filter down our data based on that condition

We can do this using `functions` like the ones we've learned about in early Python lessons that we declare using `def`. We can also do this using`lambda function` which are functions written in one line!

Below we do the same thing we did earlier to reduce our dataframe to only `"per Annum"` workers but with a bit more Python.

In [7]:
data["is_perannum?"] = data["Pay Basis"].apply(lambda x: "per annum" in str(x).lower())
data["is_perannum?"]

0          True
1          True
2          True
3          True
4          True
          ...
552933     True
552934     True
552935     True
552936    False
552937     True
Name: is_perannum?, Length: 552938, dtype: bool

In [14]:
reduced_data = data[data["is_perannum?"] == True]

Now let's re-run some of our analyses:

In [15]:
data_reduced["Base Salary"].describe()

count    338552.000000
mean      83204.647510
std       33208.713927
min           1.000000
25%       54237.750000
50%       81787.000000
75%      103771.000000
max      363346.000000
Name: Base Salary, dtype: float64

In [8]:
data.columns

Index(['Fiscal Year', 'Payroll Number', 'Agency Name', 'Last Name',
       'First Name', 'Mid Init', 'Agency Start Date', 'Work Location Borough',
       'Title Description', 'Leave Status as of June 30', 'Base Salary',
       'Pay Basis', 'Regular Hours', 'Regular Gross Paid', 'OT Hours',
       'Total OT Paid', 'Total Other Pay', 'is_perannum?'],
      dtype='str')

In [9]:
data.dtypes

Fiscal Year                     int64
Payroll Number                  int64
Agency Name                       str
Last Name                         str
First Name                        str
Mid Init                          str
Agency Start Date                 str
Work Location Borough             str
Title Description                 str
Leave Status as of June 30        str
Base Salary                   float64
Pay Basis                         str
Regular Hours                 float64
Regular Gross Paid            float64
OT Hours                      float64
Total OT Paid                 float64
Total Other Pay               float64
is_perannum?                     bool
dtype: object

In [ ]:
data['Fiscal Year'] = pd.to_datetime(
    data['Fiscal Year'].astype(str),
    format='%Y'
)

data.head()

# salaries_over_time = data.set_index('Fiscal Year')
# fiscal_year_tally = salaries_over_time.resample("YE")['Payroll Number'].count()

# fiscal_year_tally.head()

,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay
0,2023-01-01,67,ADMIN FOR CHILDREN'S SVCS,ROODE,SELENA,R,07/22/2019,BRONX,CHILD PROTECTIVE SPECIALIST,ACTIVE,65921.0,per Annum,1820.0,65977.23,6.50,244.34,4400.66
1,2023-01-01,67,ADMIN FOR CHILDREN'S SVCS,AARON,TERESA,NaN,03/21/2016,BRONX,CHILD PROTECTIVE SPECIALIST,ACTIVE,65921.0,per Annum,1820.0,65998.30,448.00,22072.10,15938.80
2,2023-01-01,67,ADMIN FOR CHILDREN'S SVCS,AARONS,CAMELIA,M,08/08/2016,BROOKLYN,CHILD PROTECTIVE SPECIALIST,ON LEAVE,65921.0,per Annum,602.0,23163.11,28.75,1295.17,8994.61
3,2023-01-01,67,ADMIN FOR CHILDREN'S SVCS,ABBASSI,MARIAM,N,11/21/2022,QUEENS,CHILD PROTECTIVE SPECIALIST,ACTIVE,55463.0,per Annum,1050.0,31082.77,27.75,928.43,3115.50
4,2023-01-01,67,ADMIN FOR CHILDREN'S SVCS,ABDEL WEDOUD,LASHAWN,NaN,04/24/2023,BROOKLYN,YOUTH DEVELOPMENT SPECIALIST,ACTIVE,50001.0,per Annum,280.0,7792.26,0.00,0.00,0.00

In [28]:
%pip install matplotlib

Collecting matplotlib
  Using cached matplotlib-3.11.2-cp314-cp314-macosx_11_0_arm64.whl.metadata (80 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.4.0-cp314-cp314-macosx_11_0_arm64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Using cached fonttools-4.67.0-cp314-cp314-macosx_10_15_universal2.whl.metadata (137 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.5.1-cp314-cp314-macosx_11_0_arm64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.25 in /Users/layla/.pyenv/versions/3.14.0/lib/python3.14/site-packages (from matplotlib) (2.5.4)
Requirement already satisfied: packaging>=20.0 in /Users/layla/.pyenv/versions/3.14.0/lib/python3.14/site-packages (from matplotlib) (26.3)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-13.0.0-cp314-cp314-macosx_11_0_arm64.whl.metadata (9.1 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.3-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: python-dateutil>=2.7 in /Users/layla/.pyenv/versions/3.14.0/lib/python3.14/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/layla/.pyenv/versions/3.14.0/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Using cached matplotlib-3.11.2-cp314-cp314-macosx_11_0_arm64.whl (9.3 MB)
Using cached contourpy-1.4.0-cp314-cp314-macosx_11_0_arm64.whl (283 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.67.0-cp314-cp314-macosx_10_15_universal2.whl (3.1 MB)
Using cached kiwisolver-1.5.1-cp314-cp314-macosx_11_0_arm64.whl (64 kB)
Downloading pillow-13.0.0-cp314-cp314-macosx_11_0_arm64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 11.6 MB/s  0:00:00 eta 0:00:01
Using cached pyparsing-3.3.3-py3-none-any.whl (126 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [matplotlib]7 [matplotlib]
Successfully installed contourpy-1.4.0 cycler-0.12.1 fonttools-4.67.0 kiwisolver-1.5.1 matplotlib-3.11.2 pillow-13.0.0 pyparsing-3.3.3

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.